;;; omarchy-colors.el --- Generated by Omarchy theme system -*- lexical-binding: t -*-
;;; Do not edit - this file is regenerated when you change themes.

(setq omarchy-color-accent "{{ accent }}")
(setq omarchy-color-cursor "{{ cursor }}")
(setq omarchy-color-fg "{{ foreground }}")
(setq omarchy-color-bg "{{ background }}")
(setq omarchy-color-sel-fg "{{ selection_foreground }}")
(setq omarchy-color-sel-bg "{{ selection_background }}")

(setq omarchy-color-black "{{ color0 }}")
(setq omarchy-color-red "{{ color1 }}")
(setq omarchy-color-green "{{ color2 }}")
(setq omarchy-color-yellow "{{ color3 }}")
(setq omarchy-color-blue "{{ color4 }}")
(setq omarchy-color-magenta "{{ color5 }}")
(setq omarchy-color-cyan "{{ color6 }}")
(setq omarchy-color-white "{{ color7 }}")
(setq omarchy-color-bright-black "{{ color8 }}")
(setq omarchy-color-bright-red "{{ color9 }}")
(setq omarchy-color-bright-green "{{ color10 }}")
(setq omarchy-color-bright-yellow "{{ color11 }}")
(setq omarchy-color-bright-blue "{{ color12 }}")
(setq omarchy-color-bright-magenta "{{ color13 }}")
(setq omarchy-color-bright-cyan "{{ color14 }}")
(setq omarchy-color-bright-white "{{ color15 }}")

;; Omarchy's semantic palette. These have no ANSI slot, so they are the only
;; source of in-between shades (comment gray, subtle backgrounds, borders).
;; omarchy-theme-color synthesizes them for legacy color0..color15 themes too,
;; so they are normally populated -- but they render empty on an install whose
;; template predates this block, and a theme may set one equal to its own
;; background. The Emacs theme blends a replacement in both cases.
(setq omarchy-color-muted "{{ muted }}")
(setq omarchy-color-selection "{{ selection }}")
(setq omarchy-color-dark-fg "{{ dark_foreground }}")
(setq omarchy-color-light-fg "{{ light_foreground }}")
(setq omarchy-color-bright-fg "{{ bright_foreground }}")
(setq omarchy-color-dark-bg "{{ dark_background }}")
(setq omarchy-color-darker-bg "{{ darker_background }}")
(setq omarchy-color-lighter-bg "{{ lighter_background }}")
(setq omarchy-color-orange "{{ orange }}")

(provide 'omarchy-colors)
;;; omarchy-colors.el ends here
